# -*- coding: utf-8 -*-
"""7logisticregression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-n1MFd03RrnImTYB9VNVZIYsagocwUcM
"""

#step1 import library
import pandas as pd
import seaborn as sns

#step 2 read dataset
df=pd.read_csv('https://raw.githubusercontent.com/YBI-Foundation/Dataset/refs/heads/main/Diabetes.csv')

df

df.head()

df.info()

df.describe()

#step3 define y (output) and x (input)
df.columns

y=df ['diabetes']
x=df[['pregnancies', 'glucose', 'diastolic', 'triceps', 'insulin', 'bmi',
       'dpf', 'age']]

sns.regplot(y='diabetes',x='glucose', logistic=True, data=df)

#step4 train and test spit
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, random_state=2529)

#step5 select model
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=1000)

#step6 train the model
model.fit(x_train,y_train)

model.intercept_

model.coef_

#step7 predict
y_pred=model.predict(x_test)

x_test

y_pred

y_test

#step8 evaluate
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)



